name: arog_movil
description: "Projecto Arog"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  table_calendar: ^3.0.9
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  another_flushbar: ^1.10.29

flutter_native_splash:
  color: "#E1E5E9FF"
  image: "assets/images/ArogV2.png"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ArogV2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/ArogV2.png
    - assets/images/Arog-1.png
    - assets/images/Arog-2.png
    - assets/images/Perfil.jpg
    - assets/images/point.png

  # Splash screen configuration
  # Optional additional parameters you might want to add:
  # android_gravity: center
  # ios_content_mode: center
  # branding: assets/images/branding.png
  # dark_mode_image: assets/images/dark_splash.png
  # dark_mode_color: "#FF000000"
